<?php

return [

    [
        "name" => "Theren",
        "height" => 1.70,
        "weight" => 65,
        "background" => "Un forestiero cresciuto lontano dalla civiltà nelle terre selvagge, riuscendo a sopravvivere anche nelle condizioni più ardue.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/a03ce-sorcererad26d-1.jpg",
        "armor_class" => 10,
        "for" => 8,
        "des" => 15,
        "cos" => 15,
        "int" => 10,
        "sag" => 8,
        "car" => 14,
    ],

    [
        "name" => "Thiala",
        "height" => 1.68,
        "weight" => 50,
        "background" => "Un eremita che ha trascorso molti anni della sua vita da solo in cerca di tranquillità e risposte.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/3f86c106ca92b10eabc019775726eb94-1.jpg",
        "armor_class" => 11,
        "for" => 8,
        "des" => 14,
        "cos" => 14,
        "int" => 10,
        "sag" => 10,
        "car" => 15,
    ],

    [
        "name" => "Lucian",
        "height" => 1.90,
        "weight" => 75,
        "background" => "Un forestiero cresciuto nelle terre selvagge, lontano dal mondo civilizzato e dalle comodità dei centri abitati e dalla tecnologia.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/fc70e9408f1caec758c1cbed58a983e5-1.jpg",
        "armor_class" => 13,
        "for" => 8,
        "des" => 14,
        "cos" => 14,
        "int" => 10,
        "sag" => 15,
        "car" => 10,
    ],

    [
        "name" => "Rhogar",
        "height" => 1.90,
        "weight" => 120,
        "background" => "Cavaliere, uno dei titoli nobiliari più bassi nella società, ma può aprire diverse strade per salire i ranghi.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/677610d1cdc872882e954eef85f4f2dc-1-1024x791-1-768x593.jpg",
        "armor_class" => 18,
        "for" => 14,
        "des" => 10,
        "cos" => 14,
        "int" => 8,
        "sag" => 10,
        "car" => 15,
    ],

    [
        "name" => "Ancalagon",
        "height" => 1.80,
        "weight" => 65,
        "background" => "Un eremita che ha trascorso la maggior parte del suo tempo in un luogo isolato, presso una piccola comunità o completamente solo, meditando e trovando, forse, le risposte che cercava.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/frank-william-elf-final-web-1024x710-2-1-1-768x533.jpg",
        "armor_class" => 10,
        "for" => 8,
        "des" => 14,
        "cos" => 14,
        "int" => 10,
        "sag" => 15,
        "car" => 10,
    ],

    [
        "name" => "Reed",
        "height" => 0.70,
        "weight" => 18,
        "background" => "Cresciuto da solo ed abbandonato, il monello ha sempre badato da solo a se stesso. Furbo, scaltro e veloce, mette la sopravvivenza davanti a tutto.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/c25248a05aca896a937d6ce0da6e7cc0-1.jpg",
        "armor_class" => 10,
        "for" => 8,
        "des" => 14,
        "cos" => 15,
        "int" => 11,
        "sag" => 12,
        "car" => 12,
    ],

    [
        "name" => "Alvyn",
        "height" => 1.70,
        "weight" => 65,
        "background" => "Un sapiente ha passato anni ed anni a studiare i segreti della tradizione arcana.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/ab12bfb08cd428ec89fbf1f27c404440-1.jpg",
        "armor_class" => 15,
        "for" => 8,
        "des" => 14,
        "cos" => 15,
        "int" => 14,
        "sag" => 12,
        "car" => 8,
    ],

    [
        "name" => "Thokk",
        "height" => 2.00,
        "weight" => 120,
        "background" => "Un forestiero che è cresciuto nelle terre selvagge, lontano dal mondo civilizzato e dalle comodità dei centri abitati e dalla tecnologia.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/Calebs-6th-Birthday-1-1.png",
        "armor_class" => 19,
        "for" => 15,
        "des" => 12,
        "cos" => 15,
        "int" => 8,
        "sag" => 10,
        "car" => 10,
    ],

    [
        "name" => "Corrin",
        "height" => 1.00,
        "weight" => 25,
        "background" => "Addestrato fin da giovane all’uso delle armi, il campo di battaglia è la sua casa.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/e33898bc7445c05d3ef28cc95243ba07-1.jpg",
        "armor_class" => 14,
        "for" => 8,
        "des" => 15,
        "cos" => 15,
        "int" => 10,
        "sag" => 13,
        "car" => 10,
    ],

    [
        "name" => "Delg",
        "height" => 1.30,
        "weight" => 75,
        "background" => "Un accolito che ha passato la sua vita a servire una divinità, fornendogli servigi che vanno discussi con il Master.",
        "image" => "https://www.quellicheilbardo.it/wp-content/uploads/2020/07/Class_-Fighter-12-dungeoncrasher-varriant_Deepwarden-2_Either-Dwarven-Defender-Lion-Spirit-Totem-Barbarian-or-Anointed-Knight-1__-Cloistered-Cleric-1024x623-1-768x467.jpeg",
        "armor_class" => 20,
        "for" => 13,
        "des" => 12,
        "cos" => 14,
        "int" => 8,
        "sag" => 15,
        "car" => 10,
    ],

];
